language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
notifications:
  email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("EGM96")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("EGM96")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
